%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# PinHole model
#Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
#Camera.fx: 852.711428194838
#Camera.fy: 852.5077837969318
#Camera.cx: 712.4427054933012
#Camera.cy: 504.1833434653063

#Camera.k1: -0.31354626060554497
#Camera.k2: 0.09345098589781448
#Camera.p1: 0.0005193080908839017
#Camera.p2: -0.001036125192584548

# FishEye model
Camera.type: "KannalaBrandt8"

# Camera calibration and distortion parameters (OpenCV) 
# OLD:
#Camera.fx: 850.4842432019186
#Camera.fy: 850.0162582504862
#Camera.cx: 709.858767338577
#Camera.cy: 518.2577914251737
#Camera.k1: -0.030271974837311137
#Camera.k2: 0.008877676747724862
#Camera.k3: 0.0005882855537084952
#Camera.k4: -0.00933897525788034

# New:
Camera.fx: 210.36472845492762
Camera.fy: 210.89059861847264
Camera.cx: 258.33593991757346
Camera.cy: 188.3301113100614
Camera.k1: 0.0035262039163929284
Camera.k2: -0.001391999021466337
Camera.k3: -0.0038304314855128565
Camera.k4: 0.000652358256868571


# Camera resolution
Camera.width: 516 #1032 #1280
Camera.height: 384 #772 #1024

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Transformation from camera to body-frame (imu)
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.00258241,  0.99976926, -0.02132522,  0.02688144,
          -0.99999662, -0.00258815, -0.00024189,  0.00277962,
          -0.00029703,  0.02132452,  0.99977256,  0.02027129,
           0.0,          0.0,          0.0,          1.0]

# IMU noise
#IMU.NoiseGyro: 0.080060128439266 # 0.004 (VINS) # 0.00016 (TUM) # 0.00016    # rad/s^0.5 
#IMU.NoiseAcc: 0.54940105867 # 0.04 (VINS) # 0.0028 (TUM) # 0.0028     # m/s^1.5
#IMU.GyroWalk: 5.25788508e-04 # 0.000022 (VINS and TUM) rad/s^1.5
#IMU.AccWalk: 0.041903074493 # 0.0004 (VINS) # 0.00086 # 0.00086    # m/s^2.
#IMU.Frequency: 150


IMU.NoiseGyro: 9.6957e-03 # 0.004 (VINS) # 0.00016 (TUM) # 0.00016    # rad/s^0.5 
IMU.NoiseAcc: 2.0875e-01 # 0.04 (VINS) # 0.0028 (TUM) # 0.0028     # m/s^1.5
IMU.GyroWalk: 5.02588e-04 # 0.000022 (VINS and TUM) rad/s^1.5
IMU.AccWalk: 1.0191e-02 # 1.0191e-03
IMU.Frequency: 150



#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500 # 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.15

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 11

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 9

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5 # -1.8
Viewer.ViewpointF: 500

#--------------------------------------------------------------------------------------------
# PointCloudMapping Parameters
#--------------------------------------------------------------------------------------------
PointCloudMapping.Resolution: 0.04

